server:
  port: ${EUREKA_PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:127.0.0.1}
    
  server:
    renewal-percent-threshold: 0.85